mysql.db.url=jdbc:mysql://localhost:3306/minesweeper_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
mysql.db.user=root
mysql.db.password=123456
